name: Docker Image CI

on: [push, workflow_dispatch]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: "DockerFile"
          tags: flasktest:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - name: Run Flask
        uses: addnab/docker-run-action@v3
        with:
          image: flasktest:latest
          run: |
            ./app.py &
            wget 0.0.0.0:8080 --output-document b.pdf

