name: Build LaTeX document
on:
  push:
    paths:
      - Source_Code/**
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          continue_on_error: true
          root_file: |
            ./Source_Code/main.tex
        env:
          TEXINPUTS: ".:./Source_Code//:"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: Bobby_Dhanoolal_Resume.pdf
